from .cmdline import COMMAND_FUNCTIONS, COMMAND_TOOLS
from .directory_list import DIRECTORY_FUNCTIONS, DIRECTORY_TOOLS
from .image_tools import IMAGE_FUNCTIONS, IMAGE_TOOLS
from .handoff import HANDOFF_FUNCTIONS, HANDOFF_TOOLS
from .web_browser import WEB_BROWSER_FUNCTIONS, WEB_BROWSER_TOOLS

# 合并所有工具元信息（供LLM识别）
TOOLS = [*COMMAND_TOOLS, *DIRECTORY_TOOLS, *WEB_BROWSER_TOOLS]

# 合并所有工具函数映射（供Agent执行）
TOOL_FUNCTIONS = {
    **COMMAND_FUNCTIONS,
    **DIRECTORY_FUNCTIONS,
    **WEB_BROWSER_FUNCTIONS,
}
