from .file_op import FILE_FUNCTIONS, FILE_TOOLS
from .cmdline import COMMAND_FUNCTIONS, COMMAND_TOOLS
from .directory_list import DIRECTORY_FUNCTIONS, DIRECTORY_TOOLS

# 合并所有工具元信息（供LLM识别）
TOOLS = [*FILE_TOOLS, *COMMAND_TOOLS, *DIRECTORY_TOOLS]

# 合并所有工具函数映射（供Agent执行）
TOOL_FUNCTIONS = {**FILE_FUNCTIONS, **COMMAND_FUNCTIONS, **DIRECTORY_FUNCTIONS}
