from .cmdline import COMMAND_FUNCTIONS, COMMAND_TOOLS
from .directory_list import DIRECTORY_FUNCTIONS, DIRECTORY_TOOLS
from .edit import EDIT_FUNCTIONS, EDIT_TOOLS
from .file_write import FILE_WRITE_FUNCTIONS, FILE_WRITE_TOOLS
from .read_file import READ_FILE_FUNCTIONS, READ_FILE_TOOLS
from .web_browser import WEB_BROWSER_FUNCTIONS, WEB_BROWSER_TOOLS

TOOLS = [
    *COMMAND_TOOLS,
    *DIRECTORY_TOOLS,
    *EDIT_TOOLS,
    *FILE_WRITE_TOOLS,
    *READ_FILE_TOOLS,
    *WEB_BROWSER_TOOLS,
]

TOOL_FUNCTIONS = {
    **COMMAND_FUNCTIONS,
    **DIRECTORY_FUNCTIONS,
    **EDIT_FUNCTIONS,
    **FILE_WRITE_FUNCTIONS,
    **READ_FILE_FUNCTIONS,
    **WEB_BROWSER_FUNCTIONS,
}
